In [3]:
import numpy as np

In [1]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr = np.array(lista)
type(arr)

numpy.ndarray

In [8]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr [1]

2

In [10]:
arr[0]+arr[5]

7

In [14]:
print(matriz[0])
matriz[0,2]

[1 2 3]


3

### Slicing

In [15]:
arr[0:3]

array([1, 2, 3])

In [16]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [17]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [24]:
arr[-2:]

array([8, 9])

### Slicing por pasos

In [22]:
arr[::2]

array([1, 3, 5, 7, 9])

In [23]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [25]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])