In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4])
#tipo de dato del array
arr.dtype

dtype('int64')

In [8]:
#asignar el tipo de dato del array con dtype
arr = np.array([1,2,3,4], dtype='float64')
#tipo de dato del array
print(arr.dtype)
arr

float64


array([1., 2., 3., 4.])

In [9]:
#cambiar el tipo de dato del array
arr = arr.astype(np.int64)
print(arr.dtype)
arr

int64


array([1, 2, 3, 4])

In [13]:
arr = np.array([0,1,2,3,4])
#cambiar el tipo de dato del array
arr = arr.astype(np.bool_)

print(arr)

[False  True  True  True  True]


In [18]:
arr = np.array([0,1,2,3,4])
#cambiar el tipo de dato del array
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [17]:
arr = np.array(['0','1','2','3','4'])
#cambiar el tipo de dato del array
arr = arr.astype(np.int8)

arr

array([0, 1, 2, 3, 4], dtype=int8)

Crear un array con un rango definido


In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Crear un array en un rango definido definiendo el numero de datos del array

In [27]:
np.linspace(0,10,10)
np.linspace()

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])